/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'custom_library' 
 * Target:  'stm32g030f6p6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* Keil::Device:Startup@1.4.0 */
#define RTE_DEVICE_STARTUP_STM32G0XX    /* Device Startup for STM32G0 */


#endif /* RTE_COMPONENTS_H */
